### ISSUE TITLE
Support Kotlin Multiplatform JVM

### ISSUE THREAD

**Issue by hfhbd** [hfhbd/serviceloader-gradle-plugin#2]
The KGP is mostly undocumented without any api docs making the implementation challenging.

**Comment by sureshg** [comment]
Recently found your project.  Have you see this one - https://github.com/ZacSweers/auto-service-ksp ? If so, are there any difference in features ?

**Comment by hfhbd** [comment]
I wasn't aware of this lib, but I do some more checks, like checking the constructor. This was my main pitfall in the past using `object` as service implementations.

**Comment by hfhbd** [comment]
And you can use the serviceloader in commonMain.
